In [2]:
import numpy as np

In [11]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [12]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
c=np.array(
    [[[1,2],
      [3,4],
      [5,6]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]]]


In [14]:
arr=np.zeros((3,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
arr=np.ones((3,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
arr=np.eye(2)
print(arr)

[[1. 0.]
 [0. 1.]]


In [19]:
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
arr=np.arange(1,15)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [21]:
arr=np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [22]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [23]:
print(arr.shape)

(2, 3)


In [24]:
print(arr.ndim)

2


In [25]:
print(arr.size)

6


In [26]:
print(arr.dtype)

int64


In [29]:
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[2])

10
30


In [30]:
print(arr[-1])

40


In [31]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,1])
print(arr[1,2])

2
6


In [32]:
arr=np.array([10,20,30,40,50,60])
print(arr[1:4])

[20 30 40]


In [33]:
print(arr[:3])

[10 20 30]


In [34]:
print(arr[3:])

[40 50 60]


In [35]:
print(arr[::2])

[10 30 50]


In [36]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [4]:
arr=np.arange(1,13)
new_arr=arr.reshape(3,4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [8]:
print(a+10)
print(a*2)

[11 12 13]
[2 4 6]


In [9]:
arr=np.array([10,20,30,40,50])
print(np.sum(arr))

150


In [10]:
print(np.mean(arr))

30.0


In [11]:
print(np.min(arr))

10


In [12]:
print(np.std(arr))

14.142135623730951
